### ISSUE TITLE
New scoring system ideas

### ISSUE THREAD

**Issue by shaunli8** [nighthawkcoders/game_levels_mp#18]
Here is a list of how the new scoring system will work. If you have any recommendations or suggestions, feel free to put it in the comments of this issue so we can agree on one unified scoring system. 

- Score will decrease over time
- Killing enemies rewards points
- "Skipping" levels or not starting from level 1 results in a huge penalty (Exact amount of point deduction not decided yet)

**Comment by MaryamAbdul-Aziz** [comment]
Maybe an extra bonus for not using special features (ex, dash, whatever other features we end up adding?)
